### ISSUE TITLE
As dependências listadas em apt-install-dependencies pode ser requeridas no composer.json

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/nfe-ws#4]

**Comment by masakik** [comment]
Sim, acho que deveria. Mas o script eu criei para fazer o deploy em um servidor novo mesmo. Até a pouco tempo não tinha esse requisito claro pois era um servidor de produção com outras coisas. Mas também o nome dos pacotes é específico para ubuntu 1804.

**Comment by masakik** [comment]
testei novamente agora e lembrei que esses pacotes são as dependencias listadas no composer install. Então para facilitar a instalação criei esse arquivo para rodar num servidor novo. Tem alguma ideia melhor?
