### ISSUE TITLE
Não valeria a pena usar PSR-4 na estrutura de diretórios? Colocar as classes em src?

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/nfe-ws#6]

**Comment by thiagogomesverissimo** [comment]
Assim, conseguiríamos colocar a lib para ser instalada via composer.

**Comment by masakik** [comment]
Certeza. Mas veja que não é uma lib e sim um webservice. O que eu fiz foi pegar a lib sped-nfe que faz tudo e colocar num webservice com as respostas que eu uso no outro sistema.
