### ISSUE TITLE
Criação de testes unitários com PHPUnit

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/nfe-ws#7]

**Comment by masakik** [comment]
Não fui totalmente iniciado nos testes unitários ainda, apesar da apresentação do @girol. Mas nesse caso específico não tenho muita ideia de como fazer os testes.

**Comment by masakik** [comment]
O ponto principal desse webservice é a comunicação com a SEFAZ (secretaria da fazenda) que necessita de um certificado tipo A1 válido. Sem isso não tem como fazer teste na comunicação. De fato a validação do XML e a geração da DANFE quem faz é o sped-nfe. Eu gero um outro documento que é um atestado de consulta que esse sim foi o plus desse projeto em relação ao sped-nfe original.

**Comment by girol** [comment]
Mas dá pra fazer teste de I/O talvez mockando os resultados, ou não?
